---
- name: "Task 1: Archive and Kafka"
  hosts: ubuntu
  become: yes
  vars:
    kafka_version: "3.9.0"
    kafka_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"

  tasks:
    - name: Ensure target directory exists
      file:
        path: /opt/tools
        state: directory
        mode: '0755'

    - name: Download Kafka archive
      get_url:
        url: "{{ kafka_url }}"
        dest: /opt/tools/kafka.tgz

    - name: Unarchive Kafka
      unarchive:
        src: /opt/tools/kafka.tgz
        dest: /opt/tools/
        remote_src: yes